language: node_js
node_js:
  - 'stable'
cache:
 - yarn 
 - npm 
  directories:
    - 'node_modules'
install: 
  - npm ci

script:
  - npm test
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true,
  github-token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: main
# install: 
# before_script:
# script:
# after_success:
# after_failure:
# after_script:
# before_deploy:
# deploy:
# after_deploy:
